{% set name = "simple-salesforce" %}
{% set version = "0.74.1" %}
{% set sha256sum = "5d4f0ac3434269cce8fbca3cc1bca82139f75a1c638eac8167e869e9c5372e53" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  script: python setup.py install --single-version-externally-managed --record=files.txt
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - requests
    - pyopenssl >=0.14
    - cryptography >=1.3.4
    - idna >=2.0.0

test:
  imports:
    - simple_salesforce

about:
  home: https://github.com/simple-salesforce/simple-salesforce
  dev_url: https://github.com/simple-salesforce/simple-salesforce
  description: 'A very simple Salesforce.com REST API client for Python'
  summary: 'Simple Salesforce is a basic Salesforce.com REST API client. The goal is to provide a very low-level interface to the API, returning an ordered dictionary of the API JSON response.'
  license: Apache-2.0
  license_family: Apache
  license_file: '{{ environ['RECIPE_DIR'] }}/LICENSE.txt'


extra:
  recipe-maintainers:
    - mariusvniekerk
