{% set name = "simple-salesforce" %}
{% set version = "1.11.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/simple-salesforce-{{ version }}.tar.gz
  sha256: cc1d3ec6ae25e89484aa8e0c02f6005ec20647b24b3b269b1005847d2cd365c8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - authlib
    - python >=3.5
    - requests >=2.22.0

test:
  imports:
    - simple_salesforce
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/simple-salesforce/simple-salesforce
  dev_url: https://github.com/simple-salesforce/simple-salesforce
  description: A very simple Salesforce.com REST API client for Python
  summary: Simple Salesforce is a basic Salesforce.com REST API client. The goal is to provide a very low-level interface to the API, returning an ordered dictionary of the API JSON response.
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mariusvniekerk
