{% set name = "simple-salesforce" %}
{% set version = "1.12.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/simple-salesforce-{{ version }}.tar.gz
  sha256: ef65f72438e3b215619f6835d3d4356e147adf3a7ece6896d239127dd6aefcd1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - requests >=2.22.0
    - cryptography
    - zeep
    - pyjwt
    - more-itertools
    - pendulum

test:
  imports:
    - simple_salesforce
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/simple-salesforce/simple-salesforce
  dev_url: https://github.com/simple-salesforce/simple-salesforce
  description: 'A very simple Salesforce.com REST API client for Python'
  summary: 'Simple Salesforce is a basic Salesforce.com REST API client. The goal is to provide a very low-level interface to the API, returning an ordered dictionary of the API JSON response.'
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mariusvniekerk
    - rxm7706
